POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "kingabdul0202@gmail.com",
    "password": "password"
}

###
GET http://localhost:3000/auth/profile HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer clwubnsss00011efoa4xvsmxu

###
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Abdulrasheed",
    "email": "kingabdul02@yahoo.com",
    "password": "password"
}

###
GET http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET http://localhost:3000/api/tweets HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET http://localhost:3000/api/my-tweets HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer clww9cz9u00019027tixq9t6y

###
GET http://localhost:3000/api/tweets/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

###
POST http://localhost:3000/api/tweets HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer clww9cz9u00019027tixq9t6y

 {
    "title": "taitle",
    "content": "conasaljdhklfhlkddfvtwfhkdhudhewent"
}

###
POST http://localhost:3000/share-tweet
Content-Type: application/json
Accept: application/json
Authorization: Bearer clwubnsss00011efoa4xvsmxu

{
  "tweetId": 1,
  "recipients": ["kingabdul0202@gmail.com", "kingabdul02@yahoo.com"]
}


###
POST http://localhost:3000/api/share-tweet HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer clwubnsss00011efoa4xvsmxu

{
  "tweetId": 1,
  "recipients": [
    {"email_address": "kingabdul0202@gmail.com"},
    {"email_address": "kingabdul02@gmail.com"}
  ]
}